MaxOhn/Bathbot

Cargo.lock, Cargo.toml, src/commands/osu/mod.rs, src/commands/osu/pp.rs, src/commands/osu/standard/mod.rs, src/messages/bot_embed.rs, src/messages/preparation/mod.rs, src/messages/preparation/pp_missing.rs
Added **pp** command ("**<pp [osu name] [number]**" calculates what score is required for the player to have <number> total pp)
=> Added pp command

src/commands/osu/mod.rs, src/commands/osu/standard/mod.rs, src/commands/osu/whatif.rs, src/messages/bot_embed.rs, src/messages/preparation/mod.rs, src/messages/preparation/whatif_pp.rs
Added **whatif** command ("**<whatif [osu name] [number]**" calculates what pp the player would have if they got a [number] pp score)
=> Added whatif command

src/commands/osu/recent/mod.rs, src/commands/osu/top/mod.rs, src/embeds/osu/mod.rs, src/embeds/osu/top.rs, src/pagination/mod.rs, src/pagination/top.rs
Fiddle around with [`MAX_TITLE_LENGTH`](https://github.com/The1Divider/Bathbot/blob/main/src/embeds/osu/top.rs#L23) & [`MAX_VERSION_LENGTH`](https://github.com/The1Divider/Bathbot/blob/main/src/embeds/osu/top.rs#L24), values were chosen semi-randomly. Wasn't sure how/where you wanted the 'condensed' keyword in [`content_with_condition`](https://github.com/The1Divider/Bathbot/blob/main/src/commands/osu/top/mod.rs#L1290) but it should probably be included somewhere. Other thing was that I wrote a commend for the slash command arg but it's probably a bit too wordy/
=> Initial `Condensed` Commit

bathbot-model/src/respektive.rs, bathbot/src/embeds/osu/osustats_counts.rs, bathbot/src/util/osu.rs
Only for osustats.respektive.pw api.
=> Added last update to osustatscounts

bathbot/src/embeds/osu/map.rs
https://user-images.githubusercontent.com/22381687/212555016-a56a4674-a5ff-4d9d-b2ce-b8e813b38ac4.mp4
=> Show precise star rating on hover

bathbot-util/src/matcher.rs, bathbot/src/commands/utility/config.rs, bathbot/src/commands/utility/skin.rs, bathbot/src/embeds/osu/profile.rs
regex seems to work as expected but you might wanna double check
=> added skins.osuck.net to whitelisted skin sites

bathbot/src/util/query/filter.rs
=> fix length scale in query

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/map.rs, bathbot-psql/src/model/osu/map.rs, bathbot/src/commands/osu/compare/mod.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/map.rs, bathbot/src/core/events/interaction/autocomplete.rs, bathbot/src/core/stats.rs, bathbot/src/manager/osu_map.rs, bathbot/src/manager/redis/mod.rs
=> add autocompleted difficulty option to /cs

.env.example, README.md
=> updated readme

bathbot/src/commands/osu/compare/mod.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/manager/redis/mod.rs
=> added index option to compare score commands

bathbot-macros/src/prefix/mod.rs, bathbot-model/src/osu_stats.rs, bathbot/src/commands/osu/map_search.rs, bathbot/src/embeds/osu/bws.rs, bathbot/src/embeds/osu/compare.rs, bathbot/src/embeds/osu/profile.rs, bathbot/src/embeds/osu/profile_compare.rs, bathbot/src/embeds/osu/ranking_countries.rs, bathbot/src/embeds/osu/top_single.rs, bathbot/src/embeds/tracking/track.rs, bathbot/src/embeds/tracking/untrack.rs
fixed clippy errors & warnings after the rust 1.67.0 update
=> made clippy happy

bathbot/src/embeds/osu/compare.rs, bathbot/src/embeds/osu/mod.rs, bathbot/src/embeds/osu/osustats_globals.rs, bathbot/src/embeds/osu/player_snipe_stats.rs, bathbot/src/embeds/osu/recent.rs, bathbot/src/embeds/osu/scores.rs, bathbot/src/embeds/osu/simulate.rs, bathbot/src/embeds/osu/top.rs, bathbot/src/embeds/osu/top_if.rs, bathbot/src/embeds/osu/top_single.rs, bathbot/src/embeds/tracking/notification.rs, bathbot/src/util/osu.rs
=> added if-fc to top /cs score & made hitresults wide

bathbot/src/manager/osu_map.rs
The frequent occurrence of "Resource temporarily unavailable (os error 11)"'s is presumably caused by the aggressive use of `FuturesUnordered` of I/O intensive tasks.
In order to try and alleviate this potential contention, this PR performs map retrieval in a regular non-async loop instead of the concurrent approach.
This is an attempt at fixing #150 and other unlisted issues.
Since handling map retrieval in a non-async manner is pretty sad, this should get reverted if the contention shows no improvement.
=> prepare maps non-async

bathbot-psql/src/impls/osu/user.rs
=> fixed serverleaderboard avg hits rounding

bathbot/src/commands/osu/simulate/mod.rs
=> consider initial map attributes of simulate command

bathbot-util/src/numbers.rs
=> fix sub .1 WithComma decimal

bathbot-psql/migrations/20230201231043_inc-version-len.down.sql, bathbot-psql/migrations/20230201231043_inc-version-len.up.sql
=> increase allowed version length from 80 to 90

Cargo.lock, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/embeds/osu/simulate.rs
=> fix simulate on taiko & mania converts

bathbot/src/commands/owner/mod.rs, bathbot/src/commands/owner/request_members.rs, bathbot/src/core/cluster.rs, bathbot/src/core/context/mod.rs, bathbot/src/core/events/interaction/mod.rs, bathbot/src/core/events/mod.rs, bathbot/src/main.rs
=> added requestmembers owner subcommand

bathbot/src/embeds/osu/recent.rs
=> fix personal best idx if too little score

bathbot/src/util/osu.rs
=> handle case of combining only one pfp

bathbot/src/commands/osu/match_costs.rs
=> filter ongoing/aborted matches from matchcosts

bathbot/src/commands/help/interaction.rs, bathbot/src/commands/songs/mod.rs
=> put song title help into embed description

bathbot/src/commands/osu/recent/score.rs
=> fix vod timestamp on fails

bathbot/src/commands/osu/pinned.rs, bathbot/src/manager/osu_scores.rs, bathbot/src/manager/redis/osu.rs, bathbot/src/pagination/top.rs
=> fixed personal best index for /pinned

bathbot/src/util/osu.rs
=> consider approved maps for pb idx

bathbot/src/commands/osu/compare/score.rs, bathbot/src/embeds/osu/compare.rs, bathbot/src/embeds/osu/scores.rs
=> show pb idx in /cs for approved/loved/qualified maps

bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/embeds/osu/compare.rs, bathbot/src/embeds/osu/recent.rs, bathbot/src/embeds/osu/scores.rs, bathbot/src/pagination/scores.rs, bathbot/src/util/osu.rs
=> add explanation in pb idx hover text

bathbot/src/embeds/osu/compare.rs, bathbot/src/embeds/osu/leaderboard.rs, bathbot/src/embeds/osu/recent.rs, bathbot/src/embeds/osu/scores.rs, bathbot/src/embeds/osu/simulate.rs, bathbot/src/embeds/osu/top_single.rs, bathbot/src/manager/osu_map.rs
=> show mapset creator name in embed footers

bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/nochoke.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/osu/top/old.rs, bathbot/src/manager/pp.rs
=> fix converts in pp calc manager by specifying mode

bathbot/src/commands/mod.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/list.rs, bathbot/src/commands/osu/recent/mod.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/embeds/osu/recent_list.rs, bathbot/src/manager/osu_map.rs, bathbot/src/manager/pp.rs, bathbot/src/pagination/mod.rs, bathbot/src/pagination/recent_list.rs
=> pre-process recent list scores & add sort option

bathbot/src/commands/osu/recent/list.rs, bathbot/src/commands/osu/recent/mod.rs
=> added option to consider map-mod pairs only once in recent list

bathbot-psql/src/model/osu/map.rs, bathbot-psql/src/model/osu/mapset.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/manager/osu_map.rs
=> dont remove maps while iterating pinned scores

bathbot/src/commands/osu/top/old.rs, bathbot/src/embeds/osu/simulate.rs, bathbot/src/pagination/mod.rs
=> fixed typo in topold version

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/rank_pp.rs
hopefully fixes #28, #35, #37, #38
=> adjustments to rank pp approx

bathbot-util/src/osu.rs, bathbot/src/commands/osu/pp.rs, bathbot/src/commands/osu/whatif.rs, bathbot/src/embeds/osu/pp_missing.rs
=> fixed small bug in pp command calculation

bathbot/src/commands/osu/claim_name.rs, bathbot/src/embeds/osu/claim_name.rs
Now checking a user's highest rank for claimname, closes #219
=> disallow names if highest rank <= 100

bathbot/src/commands/osu/claim_name.rs
=> use last playcount date if last_visit unavailable

Cargo.lock, bathbot/Cargo.toml, bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/graphs/playcount_replays.rs, bathbot/src/commands/osu/graphs/rank.rs, bathbot/src/commands/osu/graphs/top_date.rs, bathbot/src/commands/osu/graphs/top_index.rs, bathbot/src/commands/osu/graphs/top_time.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/medals/stats.rs, bathbot/src/commands/osu/snipe/country_snipe_stats.rs, bathbot/src/commands/osu/snipe/player_snipe_stats.rs, bathbot/src/commands/osu/snipe/sniped.rs
Plots all graphs through a [skia backend](https://github.com/MaxOhn/plotters-skia).
Also using plotters again to draw the strain graph.
=> use skia backend for plotting

bathbot-client/src/osu.rs, bathbot/src/commands/osu/compare/profile.rs, bathbot/src/embeds/osu/profile_compare.rs
closes #67, closes #84, closes #114, closes #124
=> added some stats to profile compare

bathbot/src/commands/osu/recent/list.rs, bathbot/src/core/commands/prefix/mod.rs
=> added rlp commands

bathbot/src/commands/osu/top/old.rs
=> allow shorthand for years in topold

bathbot/src/embeds/osu/map.rs, bathbot/src/manager/osu_user.rs
=> show gd mapper name in map command

bathbot/src/commands/osu/mapper.rs
=> added sort option to mapper command

bathbot-model/src/ranking_entries.rs, bathbot-model/src/user_stats.rs, bathbot-psql/src/impls/osu/user.rs, bathbot-psql/src/model/osu/user.rs
=> added pp per month option for serverleaderboard

bathbot/src/commands/osu/medals/missing.rs, bathbot/src/commands/osu/medals/mod.rs, bathbot/src/embeds/osu/medals_missing.rs
Added sort option to `/medal missing`, defaulting to "alphabetically".
Also added hyperlink hover text to always show rarity.
Closes #146
=> added sort option to medal missing

bathbot-psql/src/impls/osu/rank_pp.rs
=> fix(psql): fixed sign in rank approx

bathbot/src/commands/osu/medals/stats.rs
=> fix(bot): use medal rarity instead of ranking

bathbot/src/util/osu.rs
=> fix(bot): consider <100 top plays for personal pb

bathbot/src/commands/osu/rank/pp.rs
=> fix(bot): always capitalize country code in <rank title

bathbot/src/util/osu.rs
=> fix(bot): fixed pb if <100 top scores

bathbot/src/embeds/osu/serverscores.rs
=> feat(bot): added mode to serverscores entries

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/score.rs
=> fix(psql): fixed in/exclude mods for serverscores

.vscode/settings.json, bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/score.rs, bathbot/src/commands/osu/compare/mod.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/fix.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/match_live.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/songs/mod.rs, bathbot/src/commands/utility/ping.rs, bathbot/src/core/commands/origin.rs, bathbot/src/embeds/osu/mapscores.rs, bathbot/src/embeds/osu/mod.rs, bathbot/src/manager/osu_scores.rs, bathbot/src/pagination/mapscores.rs, bathbot/src/pagination/mod.rs, bathbot/src/util/check_permissions.rs, bathbot/src/util/mod.rs
=> feat(bot): added command /scores map

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/score.rs, bathbot-psql/src/model/osu/score.rs, bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/scores/user.rs
=> feat(bot,psql): allow /scores to filter by mapset status

bathbot-model/src/osu_stats.rs
=> fix(model): fixed key mod deser for osustats scores

bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/scores/user.rs, bathbot/src/manager/osu_map.rs, bathbot/src/util/query/filter.rs, bathbot/src/util/query/mod.rs, bathbot/src/util/query/operator.rs, bathbot/src/util/query/optional.rs, bathbot/src/util/query/regular_criteria.rs, bathbot/src/util/query/scores_criteria.rs, bathbot/src/util/query/searchable.rs
Also fixed some bugs in the previous `FilterCriteria` implementation.
=> feat(bot): added query option to /scores commands

Cargo.lock, bathbot/src/core/events/interaction/mod.rs
=> refactor: updated twilight

bathbot/src/commands/osu/cards.rs
=> fix(bot): consider NC for speedy /card title

bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs
=> feat(bot): added country option to /scores map

bathbot-psql/src/model/osu/score.rs, bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/scores/user.rs
=> feat(bot): added option to only keep 1 score per user

Cargo.lock, Cargo.toml, bathbot/src/commands/osu/most_played.rs, bathbot/src/core/stats.rs
- Added modals to metrics registry
- Removed username cache of `rosu-v2` so it's metric is no longer available
fixes #316
=> fix(bot): fixed metrics

bathbot-util/src/matcher.rs
=> fix(bot): fixed quotes in query

bathbot-client/src/osu.rs, bathbot-model/src/respektive.rs, bathbot/src/commands/osu/compare/profile.rs, bathbot/src/commands/osu/profile/data.rs, bathbot/src/commands/osu/rank/score.rs, bathbot/src/commands/osu/ranking/players.rs
=> perf(client): get multiple respektive users at once

bathbot/src/commands/osu/match_costs.rs, bathbot/src/embeds/osu/match_costs.rs
=> feat(bot): added /matchcost option to show avg scores

bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/embeds/osu/leaderboard.rs, bathbot/src/pagination/leaderboard.rs
closes #248 
Also fixes index bug for `<rlb`
=> feat(bot): show own score in lb embeds

bathbot/src/commands/osu/simulate/args.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/core/events/interaction/modal.rs, bathbot/src/embeds/osu/simulate.rs, bathbot/src/pagination/components.rs, bathbot/src/pagination/simulate.rs
=> feat(bot): add bpm field to clock rate modal

bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/scores/user.rs, bathbot/src/embeds/osu/serverscores.rs, bathbot/src/embeds/osu/userscores.rs, bathbot/src/manager/user_config.rs
=> feat(bot): use user config mode by default for /scores

bathbot/src/commands/osu/graphs/rank.rs
=> fix(bot): omit rank 0 in rank graph

bathbot/src/embeds/osu/profile.rs
=> feat(bot): added more user profile stats

bathbot-model/src/ranking_entries.rs, bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/configs/user.rs, bathbot-psql/src/model/configs/mod.rs, bathbot-psql/src/model/configs/skin.rs, bathbot/src/commands/utility/skin.rs, bathbot/src/embeds/utility/mod.rs, bathbot/src/embeds/utility/skins.rs, bathbot/src/manager/user_config.rs, bathbot/src/pagination/mod.rs, bathbot/src/pagination/skins.rs
=> feat(bot): added /skin all command

bathbot-util/src/matcher.rs, bathbot/src/commands/utility/skin.rs
=> feat(bot): allow github skins

bathbot/src/commands/osu/map.rs
=> Remove attribute limits for `/map`

bathbot/src/embeds/osu/osutracker_mods.rs
=> fix(bot): fixed popular mods formatting

bathbot-model/src/huismetbenen.rs, bathbot/src/active/impls/country_top.rs, bathbot/src/active/impls/leaderboard.rs, bathbot/src/active/impls/map_search.rs, bathbot/src/active/impls/match_compare.rs, bathbot/src/active/impls/medals/common.rs, bathbot/src/active/impls/medals/list.rs, bathbot/src/active/impls/nochoke.rs, bathbot/src/active/impls/osekai/rarity.rs, bathbot/src/active/impls/osustats/players.rs, bathbot/src/active/impls/osustats/scores.rs, bathbot/src/active/impls/recent_list.rs, bathbot/src/active/impls/scores/map.rs, bathbot/src/active/impls/scores/server.rs, bathbot/src/active/impls/scores/user.rs, bathbot/src/active/impls/snipe/country_list.rs, bathbot/src/active/impls/snipe/difference.rs, bathbot/src/active/impls/snipe/player_list.rs, bathbot/src/active/impls/top.rs, bathbot/src/active/impls/top_if.rs, bathbot/src/commands/osu/osustats/globals.rs, bathbot/src/commands/osu/osustats/list.rs
Adjusted all affected embeds to discord's new formatting rules.
Fixes #382
=> fix(bot): fix embed formats

bathbot/src/util/osu.rs
=> refactor(bot): adjusted completion percent

bathbot-model/src/osu_stats.rs
=> fix(model): validate osustats mods

bathbot/src/commands/osu/badges/query.rs
=> fix(bot): omit autocomplete badge if len>100

bathbot-cache/src/cache/store.rs, bathbot/src/core/context/mod.rs, bathbot/src/core/context/shutdown.rs, bathbot/src/main.rs, bathbot/src/tracking/osu/osu_queue.rs
=> fix(bot,cache): store guild shards for cold resume

bathbot/src/core/context/mod.rs, bathbot/src/core/context/shutdown.rs
=> fix(bot): store miss analyzer guilds for cold resume

bathbot-model/src/osekai.rs, bathbot/src/commands/osu/medals/medal.rs
=> feat(bot,model): remove bracketed content in medal solutions

bathbot/src/commands/osu/recent/list.rs
=> fix(bot): filter scores properly for <rl

bathbot-util/src/matcher.rs
=> feat(util): whitelist link.issou.best/skin/

bathbot-client/src/osu.rs
=> fix(client): fix deserializing missing replay

bathbot/src/active/impls/skins.rs
=> fix(bot): reduce skin all skin count to 12

Cargo.lock, bathbot/Cargo.toml, bathbot/src/commands/utility/skin.rs
=> fix(bot): check skin url for syntax violations

bathbot/src/commands/osu/rank/pp.rs
=> fix(bot): improve rank arg parsing

bathbot/src/embeds/osu/medal_stats.rs
=> feat(bot): use osekai profile as ms author url

bathbot-client/src/osu.rs
=> feat(client): break lb score ties by date

bathbot-util/src/osu.rs
=> fix(bot): filter mods properly

bathbot-util/src/osu.rs, bathbot/src/commands/osu/bookmarks/message.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/fix.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/core/context/messages.rs, bathbot/src/manager/redis/mod.rs
=> feat(bot): parse map id from embed video

bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/util/query/filter.rs, bathbot/src/util/query/impls/bookmark.rs, bathbot/src/util/query/impls/mod.rs, bathbot/src/util/query/impls/regular.rs, bathbot/src/util/query/impls/top.rs, bathbot/src/util/query/searchable.rs
=> feat(bot): reworked top query arguments

bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/old.rs
=> feat(bot): added query option to /topold

bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/osu/top/old.rs
=> feat(bot): added filter/sort options to /topold

bathbot/src/commands/osu/graphs/playcount_replays.rs
=> fix(bot): handle graph if no badges

bathbot/src/commands/osu/pp.rs
=> feat(bot): consider +pp as delta

bathbot/src/commands/osu/attributes.rs, bathbot/src/embeds/osu/attributes.rs
=> feat(bot): added clock rate option to /attributes

bathbot/src/commands/osu/fix.rs
=> feat(bot): use most recent score for /fix

Cargo.lock, bathbot-psql/migrations/20230906135717_add_render_fields.down.sql, bathbot-psql/migrations/20230906135717_add_render_fields.up.sql, bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/render.rs, bathbot-psql/src/model/render.rs, bathbot/Cargo.toml, bathbot/src/active/impls/render/settings.rs, bathbot/src/manager/replay.rs
Added a new database migration to update render settings.
Fixes #487 and closes #471
=> dep: updated rosu-render

bathbot/src/active/impls/nochoke.rs
=> feat: highlight skipped scores & sb's for <nc

bathbot/src/commands/osu/recent/score.rs
=> feat(bot): consider DT&NC/SD&PF as same for retry count

bathbot/src/commands/osu/popular/maps.rs, bathbot/src/commands/osu/popular/mod.rs
=> feat(bot): add more osutracker pp ranges

bathbot/src/commands/osu/pp.rs, bathbot/src/commands/osu/rank/mod.rs, bathbot/src/commands/osu/rank/pp.rs, bathbot/src/commands/osu/rank/score.rs, bathbot/src/embeds/osu/rank_score.rs
=> feat(bot): accept delta input for rank commands

bathbot-client/src/osu.rs, bathbot-model/src/osu_stats.rs, bathbot/src/commands/osu/osustats/globals.rs, bathbot/src/util/osu.rs
=> fix(client): fixed nc/pf as osustats mods

bathbot-model/src/twitch.rs, bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/commands/osu/recent/score.rs
=> fix(bot): use login name for twitch url

bathbot/src/commands/osu/cards.rs
Closes #481 
- Reformats `/card` help text
- Makes descriptions easier to get
- Adds more descriptions
- Refactors mania descriptions
=> feat(bot): card update

bathbot-client/src/osu.rs, bathbot-model/src/huismetbenen.rs, bathbot/src/commands/osu/snipe/player_snipe_stats.rs
=> fix(model): interpret huismetbenen date as null

bathbot/src/commands/osu/top/mod.rs
=> fix(bot): fix rb ordinal suffix

Cargo.lock
Fixes #482 via https://github.com/MaxOhn/rosu-pp-older/commit/c56257010d7e4c350dab2004aec09d81a90191ee
=> dep(bot): bumped rosu-pp-older

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/score.rs
=> fix(psql): fixed querying scores by sh/xh grade

bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/scores/user.rs
=> feat(bot): use score as default order for non-ranked /scores

bathbot/src/embeds/osu/fix_score.rs
=> feat(bot): mention mods in <fix embed

bathbot/src/util/osu.rs
=> feat(bot): list cs as keys for mania map info

bathbot/src/active/impls/edit_on_timeout/mod.rs, bathbot/src/active/impls/render/cached.rs, bathbot/src/active/mod.rs
=> feat(bot): check render ratelimit after checking cache

bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/match_costs.rs, bathbot/src/commands/osu/medals/mod.rs, bathbot/src/commands/osu/medals/recent.rs, bathbot/src/commands/osu/recent/fix.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/commands/osu/recent/mod.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/tracking/mod.rs, bathbot/src/commands/utility/roll.rs, bathbot/src/core/commands/prefix/args.rs, bathbot/src/core/commands/prefix/mod.rs, bathbot/src/core/events/message/parse.rs
=> feat(bot): allow random number input for commands

bathbot/src/active/impls/profile/mod.rs
=> feat(bot): consider config tz for peak rank

bathbot/src/active/impls/top.rs, bathbot/src/commands/osu/top/mod.rs
=> feat(bot): add map attrs sort for /top

bathbot/src/commands/owner/mod.rs, bathbot/src/commands/owner/reshard.rs, bathbot/src/core/context/mod.rs, bathbot/src/core/events/mod.rs, bathbot/src/main.rs
=> feat(bot): added /owner reshard

bathbot-util/src/tourney_badges.rs
=> feat(util): filter completionist from tourney badges

bathbot/src/active/impls/badges.rs
=> feat(bot): handle empty names in /badges

bathbot-client/src/osu.rs, bathbot-model/src/respektive.rs, bathbot/src/active/impls/profile/availability.rs, bathbot/src/commands/osu/compare/profile.rs, bathbot/src/commands/osu/rank/score.rs, bathbot/src/commands/osu/ranking/players.rs, bathbot/src/embeds/osu/profile_compare.rs
=> Add peak score rank to profile compare command

bathbot/src/active/impls/profile/availability.rs, bathbot/src/active/impls/profile/mod.rs
Add the fields `Peak score rank`, `Combined grades`, and `Top score PP` to the extended user statistics.
Also re-orders the stats to fit better.
Closes #525 in combination with #534
=> feat(bot): added & re-ordered user stats

bathbot-macros/src/message/mod.rs, bathbot-macros/src/slash/mod.rs, bathbot/src/active/impls/help/prefix.rs, bathbot/src/commands/osu/mod.rs, bathbot/src/core/commands/interaction/command.rs, bathbot/src/core/commands/interaction/mod.rs, bathbot/src/main.rs
=> feat(bot): mention slash commands

bathbot/src/commands/osu/pinned.rs
=> feat(bot): added index option to /pinned

bathbot/src/commands/osu/render.rs
=> fix(bot): fix /render score ratelimit

bathbot/src/active/impls/slash_commands.rs, bathbot/src/commands/utility/commands.rs
=> fix(bot): fixed /commands components & adjusted embed

bathbot/src/active/impls/leaderboard.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/commands/osu/recent/mod.rs, bathbot/src/manager/pp.rs
=> feat(bot): added sort option to /leaderboard

bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/active/impls/edit_on_timeout/top_score.rs, bathbot/src/active/impls/mod.rs, bathbot/src/active/impls/recent_list.rs, bathbot/src/active/impls/simulate/attrs.rs, bathbot/src/active/impls/simulate/data.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/active/impls/simulate/top_old.rs, bathbot/src/active/impls/top.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/commands/osu/simulate/parsed_map.rs, bathbot/src/embeds/osu/mod.rs, bathbot/src/embeds/osu/player_snipe_stats.rs, bathbot/src/embeds/tracking/notification.rs, bathbot/src/util/osu.rs
=> feat(bot): add file option to /simulate

bathbot-psql/src/impls/osu/user.rs, bathbot/src/commands/osu/serverleaderboard.rs, bathbot/src/manager/osu_user.rs
=> feat(bot,psql): added country option to server lb

bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/map.rs, bathbot/src/embeds/osu/bws.rs, bathbot/src/embeds/osu/profile_compare.rs
=> refactor(bot): prettify code blocks with ansi

bathbot-model/src/huismetbenen.rs
=> fix: remove score_id from huismetbenen scores

bathbot-cards/src/builder/card/info.rs
=> fix: round pfp in /card

bathbot/src/active/impls/simulate/data.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/active/impls/simulate/top_old.rs
Fixes #566 via https://github.com/MaxOhn/rosu-pp/pull/23
=> fix: use rosu-pp to generate hitresults

bathbot/src/active/impls/top.rs
=> feat: show stars in top mania

bathbot-model/src/osekai.rs
=> fix: deserialize osekai ints correctly

bathbot/src/embeds/osu/bws.rs
=> fix: hightlight bws value properly

bathbot-util/src/tourney_badges.rs
Closes #593 
Unless I'm missing something, should be pretty straightforward
=> fix: bws not ignoring playlist badges

bathbot/src/active/impls/render/cached.rs
Closes #536 
At least you didn't write remder
=> fix: silly typo :)

bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/active/impls/edit_on_timeout/top_score.rs, bathbot/src/active/impls/leaderboard.rs, bathbot/src/active/impls/scores/map.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/embeds/tracking/notification.rs, bathbot/src/util/emote.rs
=> refactor(bot): show mode in embed footer icon

bathbot/src/active/impls/higherlower/score_pp.rs, bathbot/src/active/impls/osustats/scores.rs, bathbot/src/active/impls/profile/top100_stats.rs, bathbot/src/active/impls/snipe/player_list.rs, bathbot/src/commands/osu/cards.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/nochoke.rs, bathbot/src/commands/osu/osustats/globals.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/commands/osu/recent/list.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/osu/top/old.rs, bathbot/src/embeds/osu/player_snipe_stats.rs, bathbot/src/manager/mod.rs, bathbot/src/manager/osu_map.rs, bathbot/src/manager/pp.rs, bathbot/src/util/osu.rs
This should make pp calc consider clock rate in most places.
=> feat: consider clockrate in pp calc

bathbot-cards/src/skills/description.rs, bathbot/src/commands/osu/cards.rs
=> feat: consider CL in card description

bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/active/impls/edit_on_timeout/top_score.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/embeds/tracking/notification.rs, bathbot/src/manager/pp.rs, bathbot/src/util/osu.rs
=> fix: consider clock rate in map info

bathbot/src/commands/osu/rank/pp.rs
=> refactor: max on 100th score for <rank approx

Cargo.lock, bathbot/src/active/impls/simulate/mod.rs
=> fix: consider clockrate in simulate map info

bathbot-util/src/matcher.rs, bathbot/src/commands/utility/skin.rs
=> feat: allow skin urls to osu forum

bathbot/src/active/impls/render/import.rs
=> Yuna embed

bathbot/src/embeds/tracking/notification.rs
=> fix: use score pp for max pp in tracking notif if SS

bathbot/src/active/impls/profile/availability.rs, bathbot/src/active/impls/profile/mod.rs, bathbot/src/commands/osu/profile.rs
=> fix(bot): use improved peaks for compact profile

bathbot/src/active/impls/profile/top100_stats.rs
=> fix(bot): consider mods in top100 stats

bathbot/src/active/impls/map.rs, bathbot/src/commands/osu/nochoke.rs, bathbot/src/commands/osu/recent/leaderboard.rs
=> fix(bot): consider daycore in all attribute calcs

bathbot/src/active/impls/medals/common.rs, bathbot/src/active/impls/medals/list.rs, bathbot/src/active/impls/medals/missing.rs
=> fix(bot): escape % in osekai urls

bathbot/src/commands/osu/top/if_.rs
=> fix(bot): ensure mods validity for topif

bathbot/src/commands/utility/config.rs, bathbot/src/commands/utility/server_config.rs
=> fix(bot): added score_data option to /serverconfig

bathbot-util/src/tourney_badges.rs
=> fix(util): ignore pickem badges for bws

bathbot-client/src/snipe/kittenroleplay.rs, bathbot-client/src/snipe/mod.rs, bathbot/src/commands/osu/snipe/country_snipe_list.rs, bathbot/src/commands/osu/snipe/country_snipe_stats.rs, bathbot/src/commands/osu/snipe/mod.rs, bathbot/src/commands/osu/snipe/player_snipe_list.rs, bathbot/src/commands/osu/snipe/player_snipe_stats.rs, bathbot/src/commands/osu/snipe/sniped.rs, bathbot/src/commands/osu/snipe/sniped_difference.rs, bathbot/src/embeds/osu/player_snipe_stats.rs
=> feat: add ctb snipe support

bathbot/src/embeds/osu/attributes.rs
=> feat(bot): show custom clockrate in /attributes

bathbot/src/commands/osu/graphs/snipe_count.rs, bathbot/src/commands/osu/snipe/player_snipe_list.rs, bathbot/src/commands/osu/snipe/player_snipe_stats.rs, bathbot/src/commands/osu/snipe/sniped_difference.rs
=> refactor(bot): mention mode in snipe text

bathbot/src/active/impls/compare/scores.rs
=> feat: show ratio for mania compares

bathbot/src/commands/osu/nochoke.rs
=> fix(bot): dont panic on missing nc pp

bathbot/src/util/ext/interaction_command.rs
=> fix(bot): dont remove embed on interaction timeout

bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/top/mod.rs
=> fix(bot): fix rng index on empty list

Cargo.lock
Fixes #713 via https://github.com/MaxOhn/rosu-v2/commit/8668de36fb91e4a1a1176e100a5da53efe86531a
=> fix(bot): handle catch hitresults in stable format

bathbot-client/src/snipe/mod.rs, bathbot-model/src/kittenroleplay.rs
=> fix(model,client): consider kittenroleplay nulls

bathbot/src/active/impls/help/interaction.rs
=> chore(bot): remove mention of old cmd

bathbot/src/active/impls/simulate/mod.rs, bathbot/src/util/osu.rs
=> feat(bot): consider DA mod in map info

bathbot/src/active/impls/compare/scores.rs
=> link to scores in compare embeds

bathbot-util/src/osu.rs, bathbot/src/active/impls/match_compare.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/embeds/osu/match_live.rs
Removes long-standing TODOs by cleaning up the grade-calculation interface regarding mods.
=> perf: cleanup cloning of mods

bathbot/src/commands/osu/compare/profile.rs
=> refactor: nest body of generic fn

bathbot/src/manager/redis/osu.rs
Got two bugs at once 👌 
Fixes #763
=> fix: use given mode properly

bathbot/src/commands/osu/rank/pp.rs
=> fix: use lazer scores for /rank

bathbot/src/active/impls/match_costs.rs
=> fix: format mc values better

bathbot/src/commands/osu/pinned.rs
=> feat: add reverse option to /pinned

bathbot/src/active/impls/bg_game/mod.rs
=> fix: set default for bg components

bathbot/src/active/impls/single_score.rs
=> refactor: round single score bpm

bathbot/src/active/impls/single_score.rs
=> fix: hide pagination if disabled in settings

bathbot/src/commands/utility/embed_builder.rs
=> refactor: make /builder ephemeral

bathbot/src/commands/osu/recent/score.rs, bathbot/src/core/context/mod.rs
If a user has not configured score embed settings, there's a chance that message content will be added to `/recent` (`<r`) up to some amount of times to make sure the user learns about the `/builder` command.
The percentage is currently set to 25% and the amount of times is set to 4.
=> feat: add occasional notice for /builder to <r

bathbot/src/active/impls/single_score.rs
=> feat: mention timezone in footer datetimes

bathbot-model/src/embed_builder/settings.rs, bathbot/src/active/impls/embed_builder.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/top/mod.rs
=> feat: add "image with strains" /builder option

bathbot/src/active/builder.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/tracking/osu/osu_loop.rs, bathbot/src/util/osu.rs
=> fix: handle personal best index issues

bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/commands/osu/compare/score.rs
=> feat: use embed setting for first <c score

bathbot/src/active/impls/single_score.rs
=> fix: format mods with custom clock rates again

bathbot/src/active/impls/embed_builder.rs
=> fix: dont move footer values down

bathbot/src/commands/osu/medals/medal.rs
=> feat: hide more medal data to avoid spoilers

.sqlx/query-41f23ba47497d8b21b571add24b5efc9c90def05284fbd13eea5324f2833ce02.json, .sqlx/query-56c783134577013d4ca9ef1328dba43223c3b745c1a4a5ce9148cb9d94fe9d00.json, bathbot-psql/src/impls/osu/map.rs, bathbot-psql/src/impls/osu/mapset.rs
=> fix: query for oldest version & delete outdated maps

bathbot/src/active/impls/compare/scores.rs
=> fix: show sr in <c title with multiple scores

bathbot/src/active/impls/compare/scores.rs, bathbot/src/commands/osu/compare/score.rs
=> refactor: use builder image setting for <c

bathbot/src/commands/osu/rank/pp.rs, bathbot/src/embeds/osu/pp_missing.rs
fixes #592, adds suffix to the top play index and fixes the bad grammar
=> Fix bad grammar in rank command

bathbot/src/commands/utility/embed_builder.rs
=> Fix epic typo in builder command description

bathbot/src/commands/osu/top/mod.rs
=> fix: remove incorrect content in <topn

bathbot/src/active/impls/bg_game/mod.rs, bathbot/src/active/mod.rs
=> fix: dont defer on bg start

bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/top/mod.rs
=> fix: hide render button based on settings

bathbot-model/src/embed_builder/value.rs, bathbot/src/active/impls/embed_builder.rs, bathbot/src/active/impls/single_score.rs
=> feat: add option to show max pp if fc

bathbot-model/src/embed_builder/settings.rs, bathbot-model/src/embed_builder/value.rs, bathbot/src/active/impls/embed_builder.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/tracking/osu/osu_loop.rs
=> feat: add sr value to builder

bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/map.rs
Accidently had the old preview url in the last pr
=> Have the right map preview URL for standard

bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/recent/leaderboard.rs
=> fix: use proper pfp url for lb author icon

bathbot/src/commands/osu/top/mod.rs
=> Add <t to aliases of <top

bathbot/src/active/impls/single_score.rs
=> fix: hyperlink grade emotes properly

bathbot/src/active/impls/simulate/data.rs, bathbot/src/active/impls/simulate/top_old.rs
=> fix: add lazer/stable buttons for mania sim

bathbot/src/active/impls/single_score.rs
=> fix: fix separator for ratio

Cargo.lock, bathbot-cards/src/skills/mod.rs, bathbot/src/commands/osu/cards.rs
=> fix: set_on_lazer always false for legacy scores

bathbot/src/commands/osu/simulate/args.rs, bathbot/src/commands/osu/simulate/mod.rs
=> feat: added simulate arg parsing

Cargo.lock
Fixes #890 via https://github.com/MaxOhn/rosu-v2/commit/c69baeff80c295e2cabb8d7a51b4d94770c9e0eb
=> fix: niche user deserialization error

bathbot-cards/src/skills/mod.rs
=> refactor: rescale card skill values

bathbot-util/src/matcher.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/fix.rs, bathbot/src/manager/redis/mod.rs
=> fix: consider new score urls

bathbot/src/commands/fun/bg_game/mod.rs
Hopefully fixes #888
There were some command id issues while testing which don't seem to be affecting the release version so presumable this should be fine.
=> fix: add permission check for /bg

bathbot-model/src/deser.rs, bathbot-model/src/osekai.rs
=> fix: anticipate osekai's stringified number

bathbot/src/commands/osu/bookmarks/message.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/fix.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/manager/redis/mod.rs, bathbot/src/util/osu.rs
=> feat: support forwarded messages

bathbot-psql/src/model/configs/authorities.rs, bathbot/src/commands/utility/authorities.rs, bathbot/src/commands/utility/server_config.rs
=> feat: add option to remove all authority roles

bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/map.rs
=> fix: dont overwrite map from args

bathbot/src/commands/osu/compare/mod.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/recent/mod.rs, bathbot/src/commands/osu/recent/score.rs
=> feat: add convert support for /cs & <c

bathbot/src/commands/osu/leaderboard.rs
=> feat: add convert support for /leaderboard & <lb

bathbot-util/src/matcher.rs, bathbot/src/core/context/messages.rs, bathbot/src/util/query/filter.rs
=> feat: check descriptions for single map id

bathbot-util/src/osu.rs, bathbot/src/active/impls/profile/mod.rs
=> feat: show missing score for levelup in profile

bathbot/src/commands/osu/medals/mod.rs, bathbot/src/commands/osu/medals/recent.rs
=> feat: add group filter to /medal recent

bathbot-cards/src/skills/mod.rs
=> fix: clamp acc for ctb cards

bathbot/src/commands/utility/embed_builder.rs
=> fix: only show render button if replay available

bathbot/src/active/impls/top.rs
=> feat: more precise acc if sorted by acc

bathbot/src/commands/osu/top/mod.rs
=> feat: slight improvement to sort option text

bathbot/src/commands/osu/simulate/args.rs, bathbot/src/commands/osu/simulate/mod.rs
Supersedes #843 and closes #842
=> fix: lowercase sim arg before parsing

bathbot-client/src/snipe/mod.rs, bathbot/src/active/impls/badges.rs, bathbot/src/active/impls/match_costs.rs, bathbot/src/active/impls/profile/top100_mappers.rs, bathbot/src/active/impls/snipe/difference.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/recent/leaderboard.rs
=> refactor: display user id for unknown names

bathbot-model/src/osu_stats.rs, bathbot/src/commands/osu/osustats/globals.rs
=> refactor: reverse osg order when sorted by rank

bathbot/src/active/impls/top.rs, bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/mod.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/list.rs, bathbot/src/commands/osu/top/mod.rs
=> feat: add sort option by mods count

bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/old.rs
=> feat: add sort option by pp gain/loss

bathbot-model/src/respektive.rs, bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/graphs/score_rank.rs, bathbot/src/commands/osu/rank/score.rs
=> feat: add `/graph score_rank` subcommand

bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/most_played.rs, bathbot/src/active/impls/nochoke.rs, bathbot/src/active/impls/osustats/scores.rs, bathbot/src/active/impls/profile/mod.rs, bathbot/src/active/impls/recent_list.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/active/impls/snipe/difference.rs, bathbot/src/active/impls/snipe/player_list.rs, bathbot/src/active/impls/top.rs, bathbot/src/active/impls/top_if.rs, bathbot/src/commands/osu/bws.rs, bathbot/src/commands/osu/cards.rs, bathbot/src/commands/osu/daily_challenge/user.rs, bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/rank/pp.rs, bathbot/src/embeds/osu/fix_score.rs, bathbot/src/embeds/osu/osustats_counts.rs, bathbot/src/embeds/osu/player_snipe_stats.rs, bathbot/src/embeds/osu/pp_missing.rs, bathbot/src/embeds/osu/ratio.rs, bathbot/src/embeds/osu/sniped.rs, bathbot/src/embeds/osu/whatif.rs, bathbot/src/util/ext/cached_user.rs
=> feat: show rank change in profile command

bathbot-model/src/osekai.rs, bathbot/src/active/impls/medals/recent.rs, bathbot/src/commands/osu/medals/medal.rs
=> feat: added lazer/stable availability in medal embed

bathbot/src/commands/osu/compare/mod.rs, bathbot/src/commands/osu/compare/score.rs
=> feat: add grade option to /cs

bathbot/src/tracking/osu/process_score.rs
=> fix: add jitter delay to tracking score processing

bathbot/src/embeds/osu/whatif.rs
=> refactor: be less strict in whatif

Cargo.lock, bathbot-model/src/rosu_v2/user.rs, bathbot/src/active/impls/match_compare.rs, bathbot/src/active/impls/profile/mod.rs, bathbot/src/commands/osu/match_costs.rs, bathbot/src/util/ext/cached_user.rs
=> feat: show team in compact profile

Cargo.lock, Cargo.toml, bathbot-cards/src/skills/mod.rs, bathbot/src/active/impls/simulate/data.rs, bathbot/src/active/impls/simulate/top_old.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/commands/osu/top/old.rs
Test flight for the latest pp update.
Very light test coverage this time around, bugs are not too unlikely to occur.
=> dep: use rosu-pp release candidate

bathbot/src/commands/osu/render.rs
=> feat: accept score url to render

bathbot-client/src/osustats.rs, bathbot-client/src/snipe/kittenroleplay.rs, bathbot-util/src/matcher.rs, bathbot-util/src/osu.rs, bathbot/src/commands/osu/attributes.rs, bathbot/src/commands/osu/fix.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/osustats/globals.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/commands/osu/recent/list.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/commands/osu/snipe/player_snipe_list.rs, bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/osu/top/old.rs
=> feat: allow exclusion of nm and other mods

bathbot/src/manager/osu_map.rs
As facilitated by #965, this PR prepares map concurrently again which was initially removed in #155.
Will have to see how thing are going with this.
=> perf: prepare maps concurrently

bathbot-client/src/osekai.rs, bathbot/src/active/impls/osustats/best.rs, bathbot/src/commands/osu/medals/list.rs, bathbot/src/commands/osu/medals/recent.rs, bathbot/src/commands/osu/osustats/best.rs, bathbot/src/manager/redis/mod.rs
=> fix: always deserialize archived osustats best data

bathbot/src/active/impls/match_costs.rs
=> fix: matchcost formatting (#976)

bathbot/src/active/impls/embed_builder.rs
=> feat: add note to builder render button

bathbot/src/commands/osu/top/old.rs
=> fix: rename topold version

bathbot/src/commands/osu/graphs/rank.rs
=> refactor: adjust rank graph legend position

bathbot-cache/src/model/archive.rs, bathbot-model/src/rkyv_util/time.rs, bathbot-model/src/twitch.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/utility/embed_builder.rs, bathbot/src/manager/redis/mod.rs
=> perf: redis cache twitch data

bathbot/src/commands/osu/top/if_.rs
=> refactor: dont allow -cl! for <ti

bathbot/src/commands/osu/match_costs.rs
=> feat: assign teams for 1v1 head-to-heads

bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/old.rs
Closes #982
Don't think there's much to say :p
=> feat: Add sort-by-date to topold/topif

bathbot/src/active/impls/single_score.rs
=> fix: dont hyperlink score id in field name

bathbot/src/commands/tracking/mod.rs
=> fix: prefix track index

bathbot/src/active/impls/simulate/top_old.rs
=> fix: add clockrate button to simulate

bathbot/src/core/context/shutdown.rs, bathbot/src/core/events/mod.rs, bathbot/src/main.rs
=> fix: shutdown runners before shard unwrap

bathbot/src/active/impls/profile/mod.rs
=> feat: add full team name to profile tooltip

bathbot/src/active/impls/single_score.rs
=> fix: footer formatting

bathbot/src/active/impls/compare/top.rs, bathbot/src/commands/osu/compare/common.rs
Closes #1024
Also adds content to the embed message which was missing accidentally.
=> feat: use top200 for common command

bathbot/src/commands/osu/mapper.rs
=> feat: mention top100 in mapper content

bathbot/src/active/impls/render/settings.rs
=> fix: render setting beatmap colors

Cargo.lock, bathbot/src/commands/osu/ranking/mod.rs, bathbot/src/commands/osu/ranking/players.rs
=> feat: add country option to score ranking

bathbot/src/active/impls/single_score.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/graphs/map_strains.rs, bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/top/mod.rs
=> feat: add map strains graph subcommand

bathbot/src/commands/osu/graphs/bpm.rs, bathbot/src/commands/osu/graphs/map_strains.rs, bathbot/src/commands/osu/graphs/mod.rs
=> feat: add bpm subcommand to graph

bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/graphs/top_time.rs, bathbot/src/util/monthly.rs
=> feat: add graph top order by day

Cargo.lock, Cargo.toml, bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/map.rs, bathbot/src/active/impls/simulate/data.rs, bathbot/src/active/impls/simulate/top_old.rs
This should fix the mysterious occasional downtimes
=> fix: use fastest hitresult generation

bathbot-client/src/osutrack.rs, bathbot-model/src/deser.rs, bathbot-model/src/lib.rs, bathbot-model/src/osutrack.rs, bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/graphs/osutrack/accuracy.rs, bathbot/src/commands/osu/graphs/osutrack/grades.rs, bathbot/src/commands/osu/graphs/osutrack/hit_ratios.rs, bathbot/src/commands/osu/graphs/osutrack/mod.rs, bathbot/src/commands/osu/graphs/osutrack/playcount.rs, bathbot/src/commands/osu/graphs/osutrack/pp_rank.rs, bathbot/src/commands/osu/graphs/osutrack/score.rs, bathbot/src/manager/redis/mod.rs, bathbot/src/util/monthly.rs
=> feat: add osutrack graphs

Cargo.lock, Cargo.toml, bathbot-cache/src/cache/fetch.rs, bathbot-cache/src/cache/store.rs, bathbot-client/Cargo.toml, bathbot-client/src/osu.rs, bathbot-client/src/site.rs, bathbot-model/src/lib.rs, bathbot-model/src/osu.rs, bathbot-util/Cargo.toml, bathbot-util/src/html.rs, bathbot-util/src/lib.rs, bathbot/src/active/impls/medals/list.rs, bathbot/src/active/impls/medals/missing.rs, bathbot/src/commands/osu/graphs/mod.rs, bathbot/src/commands/osu/medals/icons_image.rs, bathbot/src/commands/osu/medals/list.rs, bathbot/src/commands/osu/medals/missing.rs, bathbot/src/commands/osu/medals/mod.rs, bathbot/src/commands/osu/medals/stats.rs, bathbot/src/manager/redis/mod.rs
=> feat: add image for medal icons

bathbot-util/src/mods_fmt.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/higherlower/score_pp.rs, bathbot/src/active/impls/leaderboard.rs, bathbot/src/active/impls/nochoke.rs, bathbot/src/active/impls/osustats/best.rs, bathbot/src/active/impls/osustats/scores.rs, bathbot/src/active/impls/relax/top.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/active/impls/snipe/difference.rs, bathbot/src/active/impls/snipe/player_list.rs, bathbot/src/active/impls/top.rs, bathbot/src/active/impls/top_if.rs, bathbot/src/embeds/osu/mod.rs, bathbot/src/util/osu.rs
=> feat: use legacy mod order on stable data

Cargo.lock, bathbot/src/active/impls/match_compare.rs, bathbot/src/commands/osu/match_costs.rs, bathbot/src/embeds/osu/match_live.rs
Fixes #1044 via https://github.com/MaxOhn/rosu-v2/pull/57
=> fix: matchcost command

bathbot-client/src/osekai.rs, bathbot-model/src/osekai.rs, bathbot/src/commands/osu/badges/user.rs
=> fix: badge owner deserialization

bathbot/src/embeds/osu/claim_name.rs
=> fix: compare names without space

bathbot/src/active/impls/embed_builder.rs, bathbot/src/active/impls/single_score.rs
Rewrote the single score formatting to clean things up. This hopefully doesn't introduce any bugs 🥴 
Fixes #985
=> refactor: single score formatting rewrite

Cargo.lock, Cargo.toml
Fixes #1050 via https://github.com/MaxOhn/rosu-pp/pull/60
=> fix: fast hitresult generation

bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/top.rs, bathbot/src/commands/osu/bookmarks/message.rs, bathbot/src/commands/osu/bookmarks/slash.rs
=> feat: add list size option to bookmarks

bathbot/src/active/impls/render/cached.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/active/response.rs, bathbot/src/commands/osu/render.rs, bathbot/src/core/commands/origin.rs, bathbot/src/util/ext/interaction_command.rs
=> feat: send new reply on finished render

bathbot/src/commands/osu/compare/mod.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/nochoke.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/commands/osu/recent/list.rs, bathbot/src/commands/osu/recent/mod.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/commands/utility/config.rs
=> feat: add score data option to commands

bathbot-model/src/embed_builder/value.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/single_score.rs, bathbot/src/core/config.rs
=> fix: hyperlink grade in <c

bathbot/src/commands/osu/rank/pp.rs
=> fix: ensure full top200 for rank pp calc

Cargo.lock
=> fix: dailychallenge deserialization
