bathbot/src/commands/osu/compare/score.rs, bathbot/src/manager/redis/mod.rs
- Fixed compare score commands when no difficulty is specified
- If message retrieval for cs difficulties failed, cache an empty list
=> fixed skipped cs autocomplete & optimized no-msgs-handling

bathbot/src/commands/osu/top/mod.rs
The map's max combos were missing from the osu!api response.
fixes #148
=> filter perfect combo top filter

bathbot-client/src/twitch.rs
=> specify archived when retrieving twitch VODs

bathbot-model/src/map_leaderboard.rs, bathbot-model/src/osu_stats.rs, bathbot-model/src/score_slim.rs, bathbot-util/src/ext/mod.rs, bathbot-util/src/ext/score.rs, bathbot-util/src/lib.rs, bathbot/src/commands/osu/match_compare.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/embeds/osu/match_live.rs, bathbot/src/embeds/osu/recent.rs, bathbot/src/embeds/osu/recent_list.rs, bathbot/src/embeds/osu/scores.rs, bathbot/src/util/ext/mod.rs, bathbot/src/util/ext/score.rs, bathbot/src/util/osu.rs
Should fix #173 and implement #185 and #186.
Also splits up `ScoreExt` into sub-traits and moved them to `bathbot-util` / `bathbot-model`.
=> restructure ScoreExt & improve personal best idx

bathbot-psql/src/impls/osu/map.rs, bathbot-psql/src/model/osu/map.rs, bathbot/src/manager/osu_map.rs
Executed `UPDATE osu_map_files SET map_filepath=REPLACE(map_filepath, '<MAP_PATH>', '');` and adjusted the code to accommodate prefixing the returned filenames with the `MAP_PATH`.
=> dont include full path in stored map filenames

bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/scores/mod.rs, bathbot/src/commands/osu/scores/server.rs, bathbot/src/commands/osu/scores/user.rs
Also refactored `process_scores` to the parent module.
closes #291
=> feat(bot): added reverse option to /scores commands

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/name.rs, bathbot-psql/src/impls/osu/score.rs, bathbot-psql/src/impls/osu/user.rs, bathbot/src/manager/osu_scores.rs, bathbot/src/manager/osu_user.rs, bathbot/src/manager/redis/osu.rs
closes #295 
Since the bot can't check whether a given user is restricted in `/scores server`, it can't filter out such scores. However, in addition to removing user stats of restricted users, scores will now also be removed whenever a user or their scores are requested and the bot notices they're restricted.
=> feat(bot,psql): delete scores of restricted users

bathbot-client/src/osu.rs, bathbot-model/src/osu_stats.rs, bathbot/src/commands/osu/osustats/globals.rs, bathbot/src/embeds/osu/osustats_counts.rs, bathbot/src/pagination/osustats_globals.rs, bathbot/src/util/osu.rs
- Closes #261 
- Speeds osc up by requesting 2 ranks at a time concurrently
- Speeds osc up by only deserializing the count and not the scores
=> feat(bot): add top100 to osc

bathbot-client/src/client.rs, bathbot-client/src/lib.rs, bathbot-client/src/miss_analyzer.rs, bathbot-client/src/osu.rs, bathbot-client/src/site.rs, bathbot-util/src/constants.rs, bathbot/src/commands/osu/mod.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/core/context/mod.rs, bathbot/src/core/events/interaction/component.rs, bathbot/src/core/events/mod.rs, bathbot/src/pagination/components.rs, bathbot/src/pagination/miss_analyzer.rs, bathbot/src/pagination/mod.rs
Makes the `/rs` command interact with [Miss Analyzer](https://github.com/ThereGoesMySanity/osuMissAnalyzer).
Adds a button to notify Miss Analyzer.
=> feat(bot): miss analyzer integration

bathbot-util/src/matcher.rs
It's pretty common for people to host their lists of skins as github gists, so that should probably also be allowed.
=> Add `gist.github.com` as approved skin site

bathbot/src/embeds/osu/profile.rs, bathbot/src/embeds/utility/skins.rs
I did some testing and it seems that Discord doesn't like having the `https://` in the link tooltips. 
I think showing the link like this without the `https://` is better than straight up removing the tooltip completely. Because of that, I also added the tooltip to the skin list command.
=> Fix skin link formatting

bathbot/src/commands/osu/profile/mod.rs, bathbot/src/embeds/osu/profile.rs, bathbot/src/pagination/profile.rs
Closes #55 
Personally feel like the link actually looks kinda weird on the profile embed. An alternative could be to show the rounded one in the compact embed and show the precise acc in the User Stats embed.
=> Display precise acc on hover in profile command

bathbot/src/commands/osu/profile.rs, bathbot/src/commands/osu/recent/list.rs
Adds:
- `<fruits` as an alias for `<ctb`
- `<rpl` as an alias for `<recentlistpass`
Closes #266 and #232 
These quite literally cannot break (right?)
=> Add additional aliases for <ctb and <rlp

bathbot-util/src/constants.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/leaderboard.rs, bathbot/src/active/impls/scores/map.rs, bathbot/src/commands/osu/compare/score.rs, bathbot/src/embeds/osu/fix_score.rs
Only `/scores map` might still make use of the endpoint since the proper thumbnail url is not available at that point.
Closes #426
=> fix(bot): avoid using /thumb endpoint

bathbot-psql/sqlx-data.json, bathbot-psql/src/impls/osu/map.rs, bathbot/src/active/impls/edit_on_timeout/mod.rs, bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/active/impls/edit_on_timeout/top_score.rs, bathbot/src/active/impls/top.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/mapper.rs, bathbot/src/commands/osu/pinned.rs, bathbot/src/commands/osu/recent/leaderboard.rs, bathbot/src/commands/osu/top/mod.rs, bathbot/src/manager/osu_map.rs, bathbot/src/manager/osu_scores.rs, bathbot/src/manager/replay.rs
Adds the `Render` button to single-score top & pinned embeds.
I decided against adding the miss analyzer button on those since it would require an additional request each time and users should rather use Miss Analyzer directly for scores  like that.
=> feat(bot): add render button to single score tops

bathbot-util/src/lib.rs, bathbot-util/src/matcher.rs, bathbot-util/src/tourney_badges.rs, bathbot/src/commands/osu/bws.rs
Closes #464
Also considers some more mapping badges.
=> refactor(util): dont use regex for tourney badge filtering

bathbot/src/commands/osu/top/mod.rs
Solves issue https://github.com/MaxOhn/Bathbot/issues/407
Before:
<rb1  &nbsp; ```Most recent scores in Ricar_old's top100:```
<rb2  &nbsp; ```Most recent scores in Ricar_old's top100:```
<rb3  &nbsp; ```Most recent scores in Ricar_old's top100:```
<rb57 ```Most recent scores in Ricar_old's top100:```
After:
<rb1  &nbsp; ```Most recent score in Ricar_old's top100:```
<rb2 &nbsp;  ```2nd most recent score in Ricar_old's top100:```
<rb3 &nbsp;  ```3rd most recent score in Ricar_old's top100:```
<rb57 ```57th most recent score in Ricar_old's top100:```
Added to reverse argument too with "oldest".
=> Adjusted rb message content if index is specified (Issue #407)

bathbot/src/core/commands/prefix/args.rs
Added support for “ ” as quotes for argument parsing.
Solves issue #381
=> Added support for “', '” (Issue #381)

bathbot/src/embeds/osu/profile_compare.rs
Just something I noticed while working on the peak score rank. Most of the other stats already add commas for thousands separators.
=> Add commas to grade counts in profile compare

bathbot/src/active/impls/render/cached.rs, bathbot/src/active/mod.rs, bathbot/src/util/ext/component.rs, bathbot/src/util/ext/interaction_command.rs, bathbot/src/util/ext/modal.rs
Makes the bot no longer require the "Send message" permission to edit messages on pagination.
Also fixes pagination on ephemeral responses i.e. `/bookmark`
=> fix(bot): update component by token instead of msg

Cargo.lock
Fixes the `GetBeatmapScores` endpoint not working with mods and enhances metrics.
=> dep: bumped rosu-v2

bathbot-util/src/numbers.rs, bathbot/src/embeds/osu/profile_compare.rs
Closes #562
This adds a new `AbbreviatedScore` struct that can be used to format big numbers in a compact way. 
For now this is only used in profile compare and for score values, so it only works with u64 and also doesn't consider values greater than trillions. I'm not confident enough to correctly implement the macro magic just yet, but it would be an option to rename it to `AbbreviatedNumber` and make it work with more types, if you happen to wanna use it in more places than just score in the future.
The `B` could be misinterpreted as an 8 in code blocks, but I wasn't sure what would be a better way to abbreviate the numbers as there seem to be multiple "correct" ways. I just did whatever osu-web does for now, but feel free to change the letters to something else.
=> Abbreviate score values in profile compare

bathbot/src/commands/osu/recent/list.rs
try number 2
Closes #417, sorts fails on the same map by completion% when sorting by Length
all reviews from #600 are applied so should be fine
=> refactor(bot): add completion% sorting for fails

bathbot/src/active/impls/bookmarks.rs, bathbot/src/commands/osu/bookmarks/message.rs
Closes #450 
If user has a beatmap bookmarked and they bookmark it again, get the index of that beatmap in user's bookmarks and use that as the first page displayed
Issue: Requires requesting user's bookmarks twice, as
1. Manually inserting a beatmap into `Vec<MapBookmark>` requires creating a `MapBookmark` in place, which in turn requires an extra query by itself
2. I'm not too versed at SQL in general and PostgreSQL specifically so I don't think I can adjust the query for `.add()` to return bookmarks after the addition
Feel free to close based on that, but the base implementation works totally fine
=> feat: If user makes a duplicate bookmark, start pagination at the index of the initial one

bathbot-util/src/lib.rs, bathbot-util/src/mods_fmt.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/higherlower/score_pp.rs, bathbot/src/active/impls/leaderboard.rs, bathbot/src/active/impls/nochoke.rs, bathbot/src/active/impls/osustats/best.rs, bathbot/src/active/impls/osustats/scores.rs, bathbot/src/active/impls/snipe/player_list.rs, bathbot/src/active/impls/top.rs, bathbot/src/active/impls/top_if.rs, bathbot/src/util/osu.rs
Closes #595 
Also closes #110 as a side effect by always showing `+NM` in case of empty mods.
=> feat: display speed value in mods fmt

Cargo.lock
Bumped `rosu-v2` which now no longer panics when calculating the grade of a score.
=> fix: fix topif command

bathbot/src/embeds/osu/profile_compare.rs
It might be a bit weird to look at. If you prefer I can change the comparison to use the lower precision values instead.
=> show higher precision acc in profile compare

bathbot-model/src/score_slim.rs, bathbot-psql/src/impls/osu/score.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/edit_on_timeout/mod.rs, bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/active/impls/edit_on_timeout/top_score.rs, bathbot/src/active/impls/osustats/scores.rs, bathbot/src/active/impls/render/cached.rs, bathbot/src/commands/osu/osustats/globals.rs, bathbot/src/commands/osu/recent/score.rs, bathbot/src/commands/osu/render.rs, bathbot/src/manager/replay.rs
Seems like `Score::legacy_score_id` contains irrelevant values so `Score::id` should be used again.
Unfortunately, it seems that pinned scores have the same irrelevant value for `Score::id`, `Score::best_id`, and `Score::legacy_score_id` so those scores' ids currently never match.
=> fix: use Score::id instead of Score::legacy_score_id

Cargo.lock, bathbot/src/active/impls/profile/availability.rs, bathbot/src/active/impls/profile/top100_mappers.rs
Uses the recently de-deprecated method `Osu::users`
=> perf(bot): request multiple mapper names at once

bathbot/src/commands/osu/rank/pp.rs
Fixes #647 
Also adds the optional argument prefix `user=` or `name=` to make sure the argument is considered as name.
E.g. `<rank user=cd36 rail` will consider both arguments as names. Because one is neither a number nor a country-code-rank and the other is prefixed with `user=`.
=> fix(bot): handle ambiguous double name <rank input

bathbot-macros/src/message/mod.rs, bathbot/src/active/impls/help/interaction.rs, bathbot/src/commands/help/interaction.rs, bathbot/src/core/commands/interaction/command.rs, bathbot/src/core/commands/interaction/mod.rs, bathbot/src/core/commands/interaction/twilight_command.rs, bathbot/src/core/context/mod.rs, bathbot/src/core/context/set_commands.rs, bathbot/src/main.rs
Registers commands in a custom way instead of with the interface as provided by twilight. This should be adjusted once twilight itself supports user installs.
Also, if the flag `--no-user-installs` is specified when running the bot, user installs won't be added. Just so there's a way to boot up the bot when user installs bug out.
Closes #694
=> feat: enable user installs

bathbot/src/active/builder.rs, bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/edit_on_timeout/mod.rs, bathbot/src/active/impls/higherlower/mod.rs, bathbot/src/active/impls/render/cached.rs, bathbot/src/active/mod.rs, bathbot/src/active/response.rs, bathbot/src/commands/utility/ping.rs, bathbot/src/core/commands/origin.rs, bathbot/src/util/ext/interaction_command.rs, bathbot/src/util/ext/mod.rs
Instead of literally editing the message for interaction responses, use the interaction token instead to update via interaction api.
This fixes permission issues when editing messages in DMs and the like.
=> fix(bot): update via interaction token

bathbot/src/commands/osu/compare/score.rs, bathbot/src/commands/osu/fix.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/commands/osu/map.rs, bathbot/src/commands/osu/scores/map.rs, bathbot/src/commands/osu/simulate/mod.rs, bathbot/src/util/check_permissions.rs
Permissions of interactions in DMs don't include "View Channel" so the channel history cannot be retrieved for commands like `/map` if we check the permissions. Instead, we just don't check and always try to get the history; worst case we get a 403 error.
=> refactor(bot): dont check for view channel permission

bathbot-model/src/osu_stats.rs, bathbot-model/src/score_slim.rs, bathbot-util/src/ext/score.rs, bathbot/src/active/impls/compare/scores.rs, bathbot/src/active/impls/edit_on_timeout/recent_score.rs, bathbot/src/active/impls/edit_on_timeout/top_score.rs, bathbot/src/active/impls/higherlower/score_pp.rs, bathbot/src/active/impls/leaderboard.rs, bathbot/src/active/impls/nochoke.rs, bathbot/src/active/impls/recent_list.rs, bathbot/src/active/impls/region_top.rs, bathbot/src/active/impls/scores/map.rs, bathbot/src/active/impls/scores/server.rs, bathbot/src/active/impls/scores/user.rs, bathbot/src/active/impls/simulate/mod.rs, bathbot/src/active/impls/top.rs, bathbot/src/active/impls/top_if.rs, bathbot/src/commands/osu/leaderboard.rs, bathbot/src/embeds/osu/player_snipe_stats.rs, bathbot/src/embeds/tracking/notification.rs, bathbot/src/util/osu.rs
Closes #745
Wherever applicable, grade emotes now hyperlink to their corresponding score.
This doesn't work for:
- Scores requested as legacy data because they don't have the new kind of score id (i.e. when the config is set to `Stable`)
- Scores coming from the DB because as of now it only stores the legacy id
- Grades in embed field names because hyperlinks aren't allowed there
=> feat: hyperlink grade emotes to scores

bathbot-cache/src/model/archive.rs, bathbot-model/src/rosu_v2/user.rs, bathbot/src/commands/osu/rank/pp.rs, bathbot/src/commands/osu/rank/score.rs, bathbot/src/manager/redis/osu.rs
In case the target rank is being held by the same user (and wasn't cached), update the fetched user accordingly in case it itself came from the cache and is thus less accurate than the target rank user's data.
Fixes #660
=> fix: best-effort attempt to update `/rank` user

Cargo.lock, bathbot/Cargo.toml, bathbot/src/core/context/mod.rs, bathbot/src/core/context/osutrack.rs, bathbot/src/core/context/shutdown.rs, bathbot/src/core/context/twitch.rs, bathbot/src/core/events/mod.rs, bathbot/src/manager/guild_config.rs, bathbot/src/tracking/twitch/online_streams.rs
Switches from [flurry](https://github.com/jonhoo/flurry) to [papaya](https://github.com/ibraheemdev/papaya) for read-heavy concurrent maps/sets because of presumable slight performance gains.
Unfortunately, sets are no yet natively supported.
=> perf: switch from flurry to papaya

bathbot/src/embeds/osu/medal_stats.rs
closes #754, corrects 'Corner stone' to 'Cornerstone'
freebie, I know :P
=> Fix typo in medal stats embed

bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/map.rs
resolves #793, swaps the old `http://jmir.xyz/osu/preview.html` website with the newer `https://preview.tryz.id.vn`.
=> Swap old map preview site with a new and modern one

bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/map.rs
Noticed the old website was able to preview taiko and mania while the new one can't, so we should probably use the old one for previewing taiko and mania.
=> Use old preview websites to view other modes (except catch)

bathbot/src/active/impls/nochoke.rs
closes #252, adds the score date timestamp next to the miss count in nochoke
=> Add score date timestamp to nochoke

bathbot/src/active/impls/bookmarks.rs, bathbot/src/active/impls/map.rs
Closes #792
Looks like they dropped support for these kinds of download links so I replaced them with mirror sites.
=> feat: adjust map download links

bathbot-server/Cargo.toml, bathbot-server/src/server.rs, bathbot-server/src/standby.rs
Linking was no longer working due to "CORS Missing Allow Origin" when being redirected from osu!.
=> fix: handle cors for link redirects

Cargo.lock, bathbot/Cargo.toml
Bumped `rosu-render` to `0.3` which removes the is-banned-flag that prevented future requests when encountering the first "unauthorized" response.
Fixes #848
=> fix: dont get ordr stuck upon commissioning for banned user

bathbot-client/src/osekai.rs, bathbot-model/src/osekai.rs, bathbot/src/active/impls/medals/missing.rs, bathbot/src/commands/osu/medals/medal.rs, bathbot/src/commands/osu/medals/missing.rs, bathbot/src/commands/osu/medals/stats.rs
Osekai data for medal info, beatmaps, and comments is now requested via osekai's new inex api.
Unfortunately, that api does not yet provide medal rarity so functionality revolving around it will not work properly for the time being.
=> refactor: use osekai inex api

Cargo.lock, bathbot-cards/src/skills/mod.rs, bathbot/src/active/impls/map.rs, bathbot/src/active/impls/profile/top100_stats.rs, bathbot/src/active/impls/simulate/data.rs, bathbot/src/commands/osu/nochoke.rs, bathbot/src/commands/osu/top/if_.rs, bathbot/src/commands/osu/top/old.rs, bathbot/src/embeds/osu/attributes.rs, bathbot/src/manager/guild_config.rs, bathbot/src/manager/pp.rs, bathbot/src/util/osu.rs, bathbot/src/util/query/searchable.rs
Fixes #860
This should actually remove all incorrect usages of mod bitflags rather than full mods. And the lazer status should now also be specified wherever required (hopefully I didn't miss any).
=> fix: use full mods & specify lazer

bathbot-model/src/rosu_v2/user.rs, bathbot/src/commands/osu/daily_challenge/mod.rs, bathbot/src/commands/osu/daily_challenge/user.rs, bathbot/src/commands/osu/mod.rs, bathbot/src/util/ext/cached_user.rs
Closes #798 
A new command is probably worthwhile in the long term rather than displaying all the statistics in the extended user tab of `/profile`. Once data from https://ameobea.me/osutrack/daily-challenge/ is used, there can be more subcommands too.
=> feat: added dailychallenge command

Cargo.lock
=> dep: bump `rosu-render` to `0.4.1`

bathbot-model/src/huismetbenen.rs, bathbot-model/src/osekai.rs, bathbot-model/src/osu_stats.rs, bathbot-model/src/rkyv_util/map_boxed_slice.rs, bathbot-model/src/rkyv_util/mod.rs, bathbot-model/src/rosu_v2/user.rs
`ArchivedBox` always archives as pointer indirection whereas `ArchivedString` archives strings that are no longer than 8 bytes inline.
=> perf: archive `Box<str>` as `ArchivedString`

bathbot/src/active/impls/single_score.rs
=> fix: score button owner check

bathbot/src/active/impls/relax/top.rs, bathbot/src/commands/osu/relax/top.rs
1. Filter scores by is_best. ~~Collection is done in-place because doing otherwise would require a bit too much refactors for the scope (if even feasible)~~ changed to `Vec::retain`
2. Use the correct field for star rating (I gotta document them later)
=> hotfix: Relax intergration

bathbot/src/active/impls/relax/top.rs, bathbot/src/commands/osu/relax/top.rs
We love testing in production :)
Enables use of diffcalc for `/relax top` as Relaxation Vault does not return star rating with mods applied. Currently done per-page instead of precalculating for all pages at once as Vault's API isn't paginated and I'm slightly worried about having to calculate a thousand scores on top of having to actually retrieve them in the first place
Important caveat - this potentially affects sorting by star rating, but I'm not sure how to fix that without allowing the previous issue to persist, as if you calculate only a portion of scores (e.g. 100 at a time), some might slip through anyway
=> fix: Use diffcalc for star rating in /relax top

bathbot/src/commands/osu/relax/profile.rs, bathbot/src/commands/osu/relax/top.rs
Self-explanatory, I totally forgot to check linked users when working on this
=> fix: Missing whitespace in /relax profile with linked profiles

bathbot/src/commands/utility/embed_builder.rs, bathbot/src/util/osu.rs
Closes #744 
Removes all mentions of `PersonalBestIndex::ScoreV1ed`. Should cover all the cases of scorev1 mentions in embeds
=> fix: remove scorev1-related messages

Cargo.lock, bathbot/src/commands/osu/recent/list.rs
Fixes #1018
The heuristic was adjusted via https://github.com/MaxOhn/rosu-pp/commit/30256b8196ade362ee69d66ad37a445810551d42; the mentioned map is no longer being flagged.
Also, the `/recent list` command no longer calculates attributes on suspicious maps.
=> fix: adjust suspicion heuristic

Cargo.lock, bathbot-util/src/numbers.rs, bathbot/Cargo.toml, bathbot/src/active/impls/render/import.rs, bathbot/src/commands/osu/render.rs, bathbot/src/manager/replay.rs, bathbot/src/tracking/ordr/mod.rs
Now always adds the discord user's id into render requests. If they have their discord account linked on ordr and configured settings that are available for verified bots, those settings will always be used instead of the ones configured in Bathbot.
=> feat: use ordr preset render settings
